sudo: required
services:
- docker
language: python
python:
- '3.5'
before_install:
- docker version
- docker info
install:
- npm install newman
- pip install -r requirements.txt
- pip install nose
- pip install Flask-Testing
before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version
script:
- docker build -t besteinert/devops:swagger_server .
- docker run --name bennys_api -d -t -p 127.0.0.1:8080:8080 besteinert/devops:swagger_server
- docker ps
- count=0 && until $(curl --output /dev/null --silent --head --fail http://localhost:8080);
  do printf '.' && sleep 3 && count=$((count+1)) && if [ $count -gt 5 ]; then break;
  fi; done
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker tag swagger_server besteinert/devops:swagger_server
- docker push besteinert/devops:swagger_server
env:
  global:
  - secure: wiVjiRklX/dM23jmHi+oNVzrAHlIzw39mzlRv5NKGLd/4TWLb/ANXvVqhM4JS5PQjiwOLJTk16zaCTufO+7Bygm6k3x4CV/JJYq26txbmpROANjKJUzHPUWK0tPXf19CEGUW/mF9CVMDXw6zyTqHfCDo1CowE4My0dXjLLXTgoQ2PVAVPGvm40nUuBLGi/wjbQabyNxwRohdZqnCfbYSSxlgT9m7xue34eb7o32Kup8/aNJkG1CcGPCvIvGGGVYY0Ho/UJgWyXsoip5h91VIve5f1WPBPnNGb/aIWAclgrrnNChsdkkI8fnHNpLQmwvC+rrOnNGh8fJVuctnWEEcUoHJ+jSfxRjh5qo13uwTtCZf6jES3wS6W69ztJHM3UBCB0RSfRCYwMeK+yo4F+EhXAW3bMkfMyZtov0EfvoPk9E4OQPYzjKKTm+pAKugsortWPzebe21jtJPB9vsMK3bYdqRb3ttR4W/xezC8PSIW+7t8SGbCyCLwn73YHY6sEfRJyvttAeIzXhh4pfFkYjGdh5iFi9+bxE/Yg6IVPQXtu6NJTIKCHIhqQbO27tflHoQrwgyNc/6fgINx55y4nd2NU8xJqOcky8coZULeKeRRFye33gwXCEOArIt2JW6bDBj8kPOCntnElpUg3b1uNZneXtwU6nwQZo1Av4mKGMJSXs=
  - secure: tOV6DB4tsf2svbDRCwx63pnHUCNCaB4AVcHW+bS3AShVNmOG7o6gJTffgt9Bzx1kfDNt5K9/4PFrJ+De+5BdJsdMPRPbao8xqFG+W7b0Ptb5hQswKoxGnzZjtLeobD5FV8ImO+qyKweVn8Vzi8a/m9OkJfsql8TMAABYGD/iTesD7XEPU5GnI+a6gXAgecowZWgPvflOT3jeCL8ldKnW9pyOTN385c+GxSrSAa5tgstz5cgajiSlYk5xsr08Brm9E2LspRmN6C6knFI+fsNgMilysMoFhKgNGd7pZ8+81LR9VVzhCzgPM6Wy/1wdcBZRR/+5Asn2H4pjiuB1ex7g2Kz7so1qE9kQU0mHOHUlKUsCJa4SKOT6R+0y9BaYm//+ANBGcawyn9xyi215+fuj4GDKD9/hKzNTv4V3lcyQ3IvIa77HKNGGlalXZdVvP+XY8tcjxABy0jPi/cMwFI1mSimcW39rzynLVUHkQEesJeq547ObXNfdugmo398M/LaZbOQNR6Ch56D7iIxatPggbtIAF4iU7vx/HBvaVhwlKew6fJVKmt35Tk6Hw1ikgq25+AAbMdCqHE0ePAqhpjTBfJutZ3eG9mYVVY7LgIJjG2yk+zoa1/1eRqJt3o6CtPXpc28DMImOM6J4Z12SWKqvBEgnsxKZjzZAwZRknc11n8s=
